In [5]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
print(arr1.shape)
arr2=np.array([6,7])
print(arr2.shape)
print(arr1+arr2)

(2, 2)
(2,)
[[ 7  9]
 [ 9 11]]


In [6]:
arr1=np.arange(12).reshape(2,2,3)
print(arr1.shape)
arr2=np.arange(12)
print(arr2.shape)
print(arr1+arr2)

(2, 2, 3)
(12,)


ValueError: operands could not be broadcast together with shapes (2,2,3) (12,) 

In [15]:
arr1=np.arange(12).reshape(2,2,3)
arr1
print(arr1.shape)
arr2=np.arange(2).reshape(2,1)
# arr2
print(arr2.shape)
print(arr1+arr2)

(2, 2, 3)
(2, 1)
[[[ 0  1  2]
  [ 4  5  6]]

 [[ 6  7  8]
  [10 11 12]]]


In [16]:
arr1=np.arange(15).reshape(3,5)
arr1
print(arr1.shape)
arr2=np.arange(5).reshape(1,5)
# arr2
print(arr2.shape)
print(arr1+arr2)

(3, 5)
(1, 5)
[[ 0  2  4  6  8]
 [ 5  7  9 11 13]
 [10 12 14 16 18]]


In [17]:
arr1=np.arange(15).reshape(3,5)
arr1
print(arr1.shape)
arr2=np.arange(3).reshape(1,3)
# arr2
print(arr2.shape)
print(arr1+arr2)

(3, 5)
(1, 3)


ValueError: operands could not be broadcast together with shapes (3,5) (1,3) 

In [20]:
arr1=np.arange(1020).reshape(255,2,2)
arr1
print(arr1.shape)
arr2=np.arange(6).reshape(2,3)
# arr2
print(arr2.shape)
print(arr1+arr2)

(255, 2, 2)
(2, 3)


ValueError: operands could not be broadcast together with shapes (255,2,2) (2,3) 